window.practiceQuestions = {
  'Present Simple': [
    { sentence: 'Mariam ___ to work by bus every day.', answer: 'goes', choices: ['goes', 'is going', 'went'] },
    { sentence: 'My friends ___ football on Fridays.', answer: 'play', choices: ['plays', 'play', 'are playing'] },
    { sentence: '___ your brother speak Arabic?', answer: 'Does', choices: ['Do', 'Does', 'Is'] },
    { sentence: 'We ___ coffee in the evening.', answer: "don't drink", choices: ["doesn't drink", "don't drink", "aren't drinking"] },
  ],
  'Present Continuous': [
    { sentence: 'Please be quiet; the baby ___ .', answer: 'is sleeping', choices: ['sleeps', 'is sleeping', 'slept'] },
    { sentence: 'I ___ with my aunt this month.', answer: 'am staying', choices: ['stay', 'am staying', 'stayed'] },
    { sentence: 'They ___ for the bus right now.', answer: 'are waiting', choices: ['wait', 'are waiting', 'have waited'] },
    { sentence: '___ you meeting Layla after class?', answer: 'Are', choices: ['Do', 'Are', 'Have'] },
  ],
  'Present Perfect': [
    { sentence: 'She ___ her homework, so she can relax.', answer: 'has finished', choices: ['finished', 'has finished', 'is finishing'] },
    { sentence: 'We ___ this film before.', answer: 'have seen', choices: ['saw', 'have seen', 'are seeing'] },
    { sentence: '___ you ever visited Port Sudan?', answer: 'Have', choices: ['Did', 'Have', 'Are'] },
    { sentence: 'He ___ the email yet.', answer: "hasn't sent", choices: ["didn't send", "hasn't sent", "isn't sending"] },
  ],
  'Present Perfect Continuous': [
    { sentence: 'I ___ English for two years.', answer: 'have been studying', choices: ['study', 'have studied', 'have been studying'] },
    { sentence: 'It ___ since early this morning.', answer: 'has been raining', choices: ['rained', 'has been raining', 'is raining'] },
    { sentence: 'How long ___ they been waiting?', answer: 'have', choices: ['did', 'have', 'are'] },
    { sentence: 'She is tired because she ___ all afternoon.', answer: 'has been working', choices: ['worked', 'has been working', 'is working'] },
  ],
  'Past Simple': [
    { sentence: 'We ___ our grandparents last weekend.', answer: 'visited', choices: ['visit', 'visited', 'have visited'] },
    { sentence: 'Khalid ___ his keys yesterday.', answer: 'lost', choices: ['loses', 'lost', 'has lost'] },
    { sentence: '___ you call the teacher last night?', answer: 'Did', choices: ['Do', 'Have', 'Did'] },
    { sentence: 'They ___ home late because the bus was delayed.', answer: "didn't get", choices: ["don't get", "didn't get", "weren't get"] },
  ],
  'Past Continuous': [
    { sentence: 'I ___ dinner when you called.', answer: 'was cooking', choices: ['cooked', 'was cooking', 'have cooked'] },
    { sentence: 'The children ___ outside at 5 p.m.', answer: 'were playing', choices: ['played', 'were playing', 'are playing'] },
    { sentence: '___ she studying when the lights went out?', answer: 'Was', choices: ['Did', 'Was', 'Has'] },
    { sentence: 'While we ___, it started to rain.', answer: 'were walking', choices: ['walked', 'were walking', 'are walking'] },
  ],
  'Past Perfect': [
    { sentence: 'The film ___ before we arrived.', answer: 'had started', choices: ['started', 'has started', 'had started'] },
    { sentence: 'She was hungry because she ___ breakfast.', answer: "hadn't eaten", choices: ["didn't eat", "hadn't eaten", "hasn't eaten"] },
    { sentence: '___ they finished the work by Monday?', answer: 'Had', choices: ['Have', 'Did', 'Had'] },
    { sentence: 'By the time I called, he ___ home.', answer: 'had gone', choices: ['went', 'had gone', 'has gone'] },
  ],
  'Past Perfect Continuous': [
    { sentence: 'We ___ for an hour before the bus came.', answer: 'had been waiting', choices: ['were waiting', 'had waited', 'had been waiting'] },
    { sentence: 'He was tired because he ___ all night.', answer: 'had been driving', choices: ['drove', 'had been driving', 'has been driving'] },
    { sentence: 'How long ___ she been working there before she moved?', answer: 'had', choices: ['has', 'did', 'had'] },
    { sentence: 'The ground was wet; it ___ for hours.', answer: 'had been raining', choices: ['was raining', 'had been raining', 'has rained'] },
  ],
  'Future Simple': [
    { sentence: 'I think our team ___ the match.', answer: 'will win', choices: ['wins', 'will win', 'is winning'] },
    { sentence: 'The phone is ringing; I ___ it.', answer: 'will answer', choices: ['answered', 'will answer', 'am answer'] },
    { sentence: '___ you help me carry these books?', answer: 'Will', choices: ['Do', 'Are', 'Will'] },
    { sentence: 'She ___ forget your kindness.', answer: 'will never', choices: ['never will to', 'will never', 'does never'] },
  ],
  'Future Continuous': [
    { sentence: 'At this time tomorrow, we ___ to Cairo.', answer: 'will be flying', choices: ['will fly', 'will be flying', 'are fly'] },
    { sentence: 'He ___ at the library all afternoon.', answer: 'will be studying', choices: ['studies', 'will have studied', 'will be studying'] },
    { sentence: '___ you be using the computer tonight?', answer: 'Will', choices: ['Do', 'Will', 'Are'] },
    { sentence: 'Please call after six; I ___ before then.', answer: "won't be working", choices: ["won't work", "won't be working", "am not worked"] },
  ],
  'Future Perfect': [
    { sentence: 'By Friday, they ___ the project.', answer: 'will have completed', choices: ['will complete', 'will have completed', 'have completed'] },
    { sentence: 'I ___ the book by the end of the week.', answer: 'will have read', choices: ['will be reading', 'will have read', 'read'] },
    { sentence: '___ she have arrived by noon?', answer: 'Will', choices: ['Has', 'Will', 'Does'] },
    { sentence: 'By next year, we ___ enough money to travel.', answer: 'will have saved', choices: ['will save', 'will have saved', 'are saving'] },
  ],
  'Future Perfect Continuous': [
    { sentence: 'By June, I ___ here for five years.', answer: 'will have been working', choices: ['will work', 'will have worked', 'will have been working'] },
    { sentence: 'At 8 p.m., she ___ for ten hours.', answer: 'will have been travelling', choices: ['will travel', 'will have been travelling', 'has been travelling'] },
    { sentence: 'How long ___ they have been studying by then?', answer: 'will', choices: ['have', 'will', 'do'] },
    { sentence: 'By lunchtime, he ___ for three hours.', answer: 'will have been driving', choices: ['will drive', 'will be driving', 'will have been driving'] },
  ],
};

window.extraPracticeQuestions = {
  'Present Simple': [
    { sentence: 'Water ___ at 100°C at sea level.', answer: 'boils', choices: ['boils', 'is boiling', 'boiled'] },
    { sentence: 'Rami and I ___ near the university.', answer: 'live', choices: ['lives', 'live', 'are living'] },
    { sentence: 'My sister ___ not drive at night.', answer: 'does', choices: ['do', 'does', 'is'] },
    { sentence: 'How often ___ your parents visit you?', answer: 'do', choices: ['does', 'do', 'are'] },
    { sentence: 'Salma ___ English every evening.', answer: 'studies', choices: ['study', 'studies', 'is studying'] },
    { sentence: 'Birds often ___ south in winter.', answer: 'migrate', choices: ['migrates', 'migrate', 'are migrating'] },
  ],
  'Present Continuous': [
    { sentence: 'They ___ a new bridge this year.', answer: 'are building', choices: ['build', 'are building', 'built'] },
    { sentence: 'Why ___ he wearing a coat indoors?', answer: 'is', choices: ['does', 'is', 'has'] },
    { sentence: 'Look! It ___ to snow.', answer: 'is beginning', choices: ['begins', 'is beginning', 'began'] },
    { sentence: 'At present, I ___ for my exams.', answer: 'am preparing', choices: ['prepare', 'am preparing', 'prepared'] },
    { sentence: 'She ___ not working today.', answer: 'is', choices: ['does', 'is', 'has'] },
    { sentence: 'We ___ dinner with our cousins tonight.', answer: 'are having', choices: ['have', 'are having', 'had'] },
  ],
  'Present Perfect': [
    { sentence: 'I ___ already eaten, thank you.', answer: 'have', choices: ['did', 'have', 'am'] },
    { sentence: 'She has ___ the letter.', answer: 'written', choices: ['wrote', 'written', 'writing'] },
    { sentence: 'They ___ never flown in a plane.', answer: 'have', choices: ['did', 'have', 'are'] },
    { sentence: 'How many books ___ you read this month?', answer: 'have', choices: ['did', 'have', 'do'] },
    { sentence: 'We ___ not seen that teacher before.', answer: 'have', choices: ['did', 'have', 'are'] },
    { sentence: 'The shop has just ___ .', answer: 'opened', choices: ['open', 'opened', 'opening'] },
  ],
  'Present Perfect Continuous': [
    { sentence: 'He ___ been learning to drive since April.', answer: 'has', choices: ['have', 'has', 'is'] },
    { sentence: 'We have been ___ for the exam all week.', answer: 'revising', choices: ['revise', 'revised', 'revising'] },
    { sentence: '___ it been raining long?', answer: 'Has', choices: ['Have', 'Has', 'Is'] },
    { sentence: 'They ___ been living here for six months.', answer: 'have', choices: ['has', 'have', 'are'] },
    { sentence: 'Why are your hands dirty? ___ you been gardening?', answer: 'Have', choices: ['Did', 'Have', 'Are'] },
    { sentence: 'My eyes are tired because I ___ been looking at a screen.', answer: 'have', choices: ['am', 'have', 'had'] },
  ],
  'Past Simple': [
    { sentence: 'She ___ a new phone two days ago.', answer: 'bought', choices: ['buys', 'bought', 'has bought'] },
    { sentence: 'We ___ the museum during our trip.', answer: 'visited', choices: ['visit', 'visited', 'have visited'] },
    { sentence: 'Where ___ you put my notebook?', answer: 'did', choices: ['do', 'have', 'did'] },
    { sentence: 'He ___ not understand the question.', answer: 'did', choices: ['does', 'was', 'did'] },
    { sentence: 'The meeting ___ at 9 and ended at 10.', answer: 'began', choices: ['begins', 'began', 'has begun'] },
    { sentence: 'I ___ my old teacher at the market yesterday.', answer: 'saw', choices: ['see', 'saw', 'have seen'] },
  ],
  'Past Continuous': [
    { sentence: 'At midnight, the neighbours ___ music.', answer: 'were playing', choices: ['played', 'were playing', 'are playing'] },
    { sentence: 'I ___ not paying attention when the bell rang.', answer: 'was', choices: ['did', 'was', 'am'] },
    { sentence: 'What ___ you doing when I sent the message?', answer: 'were', choices: ['did', 'were', 'have'] },
    { sentence: 'The sun ___ while we drove through the hills.', answer: 'was setting', choices: ['set', 'was setting', 'has set'] },
    { sentence: 'They ___ dinner while their children were studying.', answer: 'were making', choices: ['made', 'were making', 'make'] },
    { sentence: 'It ___ heavily when the match started.', answer: 'was raining', choices: ['rained', 'was raining', 'is raining'] },
  ],
  'Past Perfect': [
    { sentence: 'I ___ never seen snow before that trip.', answer: 'had', choices: ['have', 'did', 'had'] },
    { sentence: 'After the guests ___, we cleaned the room.', answer: 'had left', choices: ['left', 'had left', 'have left'] },
    { sentence: 'She ___ not heard the news before I told her.', answer: 'had', choices: ['has', 'did', 'had'] },
    { sentence: 'The lesson had ___ by the time I arrived.', answer: 'begun', choices: ['began', 'begun', 'beginning'] },
    { sentence: '___ you finished the report before the meeting?', answer: 'Had', choices: ['Did', 'Have', 'Had'] },
    { sentence: 'He missed the bus because he ___ up late.', answer: 'had woken', choices: ['woke', 'had woken', 'has woken'] },
  ],
  'Past Perfect Continuous': [
    { sentence: 'She ___ been teaching for years before she retired.', answer: 'had', choices: ['has', 'was', 'had'] },
    { sentence: 'I was exhausted because I ___ been running.', answer: 'had', choices: ['have', 'was', 'had'] },
    { sentence: 'They had been ___ for an hour when help arrived.', answer: 'calling', choices: ['call', 'called', 'calling'] },
    { sentence: 'How long ___ he been working there before he moved?', answer: 'had', choices: ['did', 'has', 'had'] },
    { sentence: 'The children ___ been playing outside before it got dark.', answer: 'had', choices: ['were', 'have', 'had'] },
    { sentence: 'We had been ___ for the results all morning.', answer: 'waiting', choices: ['wait', 'waited', 'waiting'] },
  ],
  'Future Simple': [
    { sentence: 'I promise I ___ tell anyone your secret.', answer: "won't", choices: ["don't", "won't", "haven't"] },
    { sentence: 'Perhaps the weather ___ improve tomorrow.', answer: 'will', choices: ['is', 'does', 'will'] },
    { sentence: 'She ___ probably arrive before us.', answer: 'will', choices: ['does', 'will', 'has'] },
    { sentence: '“I am cold.” “I ___ close the window.”', answer: 'will', choices: ['am', 'did', 'will'] },
    { sentence: '___ they join us for dinner?', answer: 'Will', choices: ['Do', 'Are', 'Will'] },
    { sentence: 'I think you ___ enjoy this book.', answer: 'will', choices: ['are', 'will', 'have'] },
  ],
  'Future Continuous': [
    { sentence: 'At 10 tomorrow morning, she ___ an interview.', answer: 'will be having', choices: ['will have', 'will be having', 'has'] },
    { sentence: 'This time next month, I ___ in a new office.', answer: 'will be working', choices: ['will work', 'will be working', 'worked'] },
    { sentence: 'They ___ not be staying with us next week.', answer: 'will', choices: ['do', 'will', 'are'] },
    { sentence: 'What ___ you be doing at lunchtime?', answer: 'will', choices: ['do', 'are', 'will'] },
    { sentence: 'The team ___ be travelling overnight.', answer: 'will', choices: ['are', 'will', 'has'] },
    { sentence: 'At 7 p.m., we ___ be eating dinner.', answer: 'will', choices: ['will', 'are', 'have'] },
  ],
  'Future Perfect': [
    { sentence: 'By the time you arrive, I ___ have cooked dinner.', answer: 'will', choices: ['do', 'will', 'have'] },
    { sentence: 'She will have ___ the course by July.', answer: 'completed', choices: ['complete', 'completed', 'completing'] },
    { sentence: 'They ___ not have reached the village before dark.', answer: 'will', choices: ['do', 'will', 'have'] },
    { sentence: '___ you have finished your work by 5 o’clock?', answer: 'Will', choices: ['Do', 'Have', 'Will'] },
    { sentence: 'By next spring, the builders ___ have repaired the roof.', answer: 'will', choices: ['are', 'will', 'have'] },
    { sentence: 'He ___ have saved enough by the end of the year.', answer: 'will', choices: ['has', 'does', 'will'] },
  ],
  'Future Perfect Continuous': [
    { sentence: 'By September, she will have been ___ French for a year.', answer: 'studying', choices: ['study', 'studied', 'studying'] },
    { sentence: 'They ___ have been travelling for twelve hours by then.', answer: 'will', choices: ['have', 'are', 'will'] },
    { sentence: 'By noon, I will have been ___ since dawn.', answer: 'working', choices: ['work', 'worked', 'working'] },
    { sentence: '___ he have been waiting long by the time we arrive?', answer: 'Will', choices: ['Has', 'Does', 'Will'] },
    { sentence: 'Next year, we will have been ___ in this house for a decade.', answer: 'living', choices: ['live', 'lived', 'living'] },
    { sentence: 'At 6 o’clock, the staff ___ have been preparing for eight hours.', answer: 'will', choices: ['have', 'are', 'will'] },
  ],
};
